// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: functions.proto

package function

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// support data types
type DataType int32

const (
	DataType_Int8        DataType = 0
	DataType_UInt8       DataType = 1
	DataType_Int16       DataType = 2
	DataType_UInt16      DataType = 3
	DataType_Int32       DataType = 4
	DataType_UInt32      DataType = 5
	DataType_Int         DataType = 6
	DataType_UInt        DataType = 7
	DataType_Int64       DataType = 8
	DataType_UInt64      DataType = 9
	DataType_Float       DataType = 10
	DataType_Double      DataType = 11
	DataType_String      DataType = 12
	DataType_Bytes       DataType = 13
	DataType_Bool        DataType = 14
	DataType_IntegerBool DataType = 15
	DataType_Datatime    DataType = 16
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "Int8",
		1:  "UInt8",
		2:  "Int16",
		3:  "UInt16",
		4:  "Int32",
		5:  "UInt32",
		6:  "Int",
		7:  "UInt",
		8:  "Int64",
		9:  "UInt64",
		10: "Float",
		11: "Double",
		12: "String",
		13: "Bytes",
		14: "Bool",
		15: "IntegerBool",
		16: "Datatime",
	}
	DataType_value = map[string]int32{
		"Int8":        0,
		"UInt8":       1,
		"Int16":       2,
		"UInt16":      3,
		"Int32":       4,
		"UInt32":      5,
		"Int":         6,
		"UInt":        7,
		"Int64":       8,
		"UInt64":      9,
		"Float":       10,
		"Double":      11,
		"String":      12,
		"Bytes":       13,
		"Bool":        14,
		"IntegerBool": 15,
		"Datatime":    16,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_functions_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_functions_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{0}
}

type Image_ImageFormat int32

const (
	Image_RGB888 Image_ImageFormat = 0
	Image_RGB565 Image_ImageFormat = 1
	Image_RGB555 Image_ImageFormat = 2
	Image_YUV420 Image_ImageFormat = 3
	Image_YUV422 Image_ImageFormat = 4
	Image_YUV444 Image_ImageFormat = 5
)

// Enum value maps for Image_ImageFormat.
var (
	Image_ImageFormat_name = map[int32]string{
		0: "RGB888",
		1: "RGB565",
		2: "RGB555",
		3: "YUV420",
		4: "YUV422",
		5: "YUV444",
	}
	Image_ImageFormat_value = map[string]int32{
		"RGB888": 0,
		"RGB565": 1,
		"RGB555": 2,
		"YUV420": 3,
		"YUV422": 4,
		"YUV444": 5,
	}
)

func (x Image_ImageFormat) Enum() *Image_ImageFormat {
	p := new(Image_ImageFormat)
	*p = x
	return p
}

func (x Image_ImageFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Image_ImageFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_functions_proto_enumTypes[1].Descriptor()
}

func (Image_ImageFormat) Type() protoreflect.EnumType {
	return &file_functions_proto_enumTypes[1]
}

func (x Image_ImageFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Image_ImageFormat.Descriptor instead.
func (Image_ImageFormat) EnumDescriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{5, 0}
}

// drop is the data running in the ruleengine
// there are three types of drop, device drop, audio drop and image drop
// device drop contains the device data from devices, such as modbus device, opc device and other devices
// audio drop contains audio frames
// image drop contains vedio
type Drop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Drop:
	//	*Drop_DeviceDrop
	//	*Drop_AudioDrop
	//	*Drop_ImageDrop
	Drop      isDrop_Drop `protobuf_oneof:"drop"`
	Timestamp int64       `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Continue  bool        `protobuf:"varint,5,opt,name=continue,proto3" json:"continue,omitempty"`
}

func (x *Drop) Reset() {
	*x = Drop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drop) ProtoMessage() {}

func (x *Drop) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drop.ProtoReflect.Descriptor instead.
func (*Drop) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{0}
}

func (m *Drop) GetDrop() isDrop_Drop {
	if m != nil {
		return m.Drop
	}
	return nil
}

func (x *Drop) GetDeviceDrop() *DeviceDrop {
	if x, ok := x.GetDrop().(*Drop_DeviceDrop); ok {
		return x.DeviceDrop
	}
	return nil
}

func (x *Drop) GetAudioDrop() *AudioDrop {
	if x, ok := x.GetDrop().(*Drop_AudioDrop); ok {
		return x.AudioDrop
	}
	return nil
}

func (x *Drop) GetImageDrop() *ImageDrop {
	if x, ok := x.GetDrop().(*Drop_ImageDrop); ok {
		return x.ImageDrop
	}
	return nil
}

func (x *Drop) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Drop) GetContinue() bool {
	if x != nil {
		return x.Continue
	}
	return false
}

type isDrop_Drop interface {
	isDrop_Drop()
}

type Drop_DeviceDrop struct {
	DeviceDrop *DeviceDrop `protobuf:"bytes,1,opt,name=deviceDrop,proto3,oneof"`
}

type Drop_AudioDrop struct {
	AudioDrop *AudioDrop `protobuf:"bytes,2,opt,name=audioDrop,proto3,oneof"`
}

type Drop_ImageDrop struct {
	ImageDrop *ImageDrop `protobuf:"bytes,3,opt,name=imageDrop,proto3,oneof"`
}

func (*Drop_DeviceDrop) isDrop_Drop() {}

func (*Drop_AudioDrop) isDrop_Drop() {}

func (*Drop_ImageDrop) isDrop_Drop() {}

type Properties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datatype   DataType `protobuf:"varint,1,opt,name=datatype,proto3,enum=functions.DataType" json:"datatype,omitempty"`
	Properties []string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
}

func (x *Properties) Reset() {
	*x = Properties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Properties) ProtoMessage() {}

func (x *Properties) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Properties.ProtoReflect.Descriptor instead.
func (*Properties) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{1}
}

func (x *Properties) GetDatatype() DataType {
	if x != nil {
		return x.Datatype
	}
	return DataType_Int8
}

func (x *Properties) GetProperties() []string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeviceDropItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID string `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	// key can be module.property or single property
	Properties map[string]*Properties `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DeviceDropItem) Reset() {
	*x = DeviceDropItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceDropItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDropItem) ProtoMessage() {}

func (x *DeviceDropItem) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDropItem.ProtoReflect.Descriptor instead.
func (*DeviceDropItem) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceDropItem) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *DeviceDropItem) GetProperties() map[string]*Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeviceDrop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*DeviceDropItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *DeviceDrop) Reset() {
	*x = DeviceDrop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDrop) ProtoMessage() {}

func (x *DeviceDrop) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDrop.ProtoReflect.Descriptor instead.
func (*DeviceDrop) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceDrop) GetItems() []*DeviceDropItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AudioDrop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audio      []byte `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	SampleRate int32  `protobuf:"varint,2,opt,name=sampleRate,proto3" json:"sampleRate,omitempty"`
}

func (x *AudioDrop) Reset() {
	*x = AudioDrop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDrop) ProtoMessage() {}

func (x *AudioDrop) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDrop.ProtoReflect.Descriptor instead.
func (*AudioDrop) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{4}
}

func (x *AudioDrop) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *AudioDrop) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format Image_ImageFormat `protobuf:"varint,1,opt,name=format,proto3,enum=functions.Image_ImageFormat" json:"format,omitempty"`
	Width  int32             `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32             `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Data   []byte            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{5}
}

func (x *Image) GetFormat() Image_ImageFormat {
	if x != nil {
		return x.Format
	}
	return Image_RGB888
}

func (x *Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImageDrop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []*Image `protobuf:"bytes,1,rep,name=image,proto3" json:"image,omitempty"`
}

func (x *ImageDrop) Reset() {
	*x = ImageDrop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDrop) ProtoMessage() {}

func (x *ImageDrop) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDrop.ProtoReflect.Descriptor instead.
func (*ImageDrop) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{6}
}

func (x *ImageDrop) GetImage() []*Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type ObjectCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectID  string   `protobuf:"bytes,1,opt,name=objectID,proto3" json:"objectID,omitempty"`
	Property  []string `protobuf:"bytes,2,rep,name=property,proto3" json:"property,omitempty"`
	Aggregate string   `protobuf:"bytes,3,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	RawSQL    string   `protobuf:"bytes,4,opt,name=rawSQL,proto3" json:"rawSQL,omitempty"`
}

func (x *ObjectCondition) Reset() {
	*x = ObjectCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectCondition) ProtoMessage() {}

func (x *ObjectCondition) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectCondition.ProtoReflect.Descriptor instead.
func (*ObjectCondition) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectCondition) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *ObjectCondition) GetProperty() []string {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *ObjectCondition) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

func (x *ObjectCondition) GetRawSQL() string {
	if x != nil {
		return x.RawSQL
	}
	return ""
}

type GeneratorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start            int64              `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End              int64              `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Interval         int64              `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	ObjectConditions []*ObjectCondition `protobuf:"bytes,4,rep,name=objectConditions,proto3" json:"objectConditions,omitempty"`
}

func (x *GeneratorRequest) Reset() {
	*x = GeneratorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorRequest) ProtoMessage() {}

func (x *GeneratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorRequest.ProtoReflect.Descriptor instead.
func (*GeneratorRequest) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{8}
}

func (x *GeneratorRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GeneratorRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *GeneratorRequest) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *GeneratorRequest) GetObjectConditions() []*ObjectCondition {
	if x != nil {
		return x.ObjectConditions
	}
	return nil
}

type ProbeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []string `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{9}
}

func (x *ProbeRequest) GetObjects() []string {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ObjectItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Datatype DataType `protobuf:"varint,2,opt,name=datatype,proto3,enum=functions.DataType" json:"datatype,omitempty"`
}

func (x *ObjectItem) Reset() {
	*x = ObjectItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectItem) ProtoMessage() {}

func (x *ObjectItem) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectItem.ProtoReflect.Descriptor instead.
func (*ObjectItem) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{10}
}

func (x *ObjectItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectItem) GetDatatype() DataType {
	if x != nil {
		return x.Datatype
	}
	return DataType_Int8
}

type ObjectDefination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectID string        `protobuf:"bytes,1,opt,name=objectID,proto3" json:"objectID,omitempty"`
	Items    []*ObjectItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ObjectDefination) Reset() {
	*x = ObjectDefination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectDefination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDefination) ProtoMessage() {}

func (x *ObjectDefination) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDefination.ProtoReflect.Descriptor instead.
func (*ObjectDefination) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{11}
}

func (x *ObjectDefination) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *ObjectDefination) GetItems() []*ObjectItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProbeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*ObjectDefination `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_functions_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_functions_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_functions_proto_rawDescGZIP(), []int{12}
}

func (x *ProbeResponse) GetObjects() []*ObjectDefination {
	if x != nil {
		return x.Objects
	}
	return nil
}

var File_functions_proto protoreflect.FileDescriptor

var file_functions_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xed, 0x01, 0x0a,
	0x04, 0x44, 0x72, 0x6f, 0x70, 0x12, 0x37, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x72, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x72, 0x6f, 0x70,
	0x48, 0x00, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x12, 0x34,
	0x0a, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x72, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x44, 0x72, 0x6f, 0x70, 0x48, 0x00, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x44, 0x72, 0x6f, 0x70, 0x12, 0x34, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x72, 0x6f,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x48, 0x00, 0x52,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x69, 0x6e, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x69, 0x6e, 0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x72, 0x6f, 0x70, 0x22, 0x5d, 0x0a, 0x0a,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0xcd, 0x01, 0x0a, 0x0e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x49, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x54, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3d, 0x0a, 0x0a, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x41, 0x0a, 0x09, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x44, 0x72, 0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x22, 0xd6, 0x01,
	0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x55, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x47, 0x42, 0x38, 0x38, 0x38, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x47,
	0x42, 0x35, 0x36, 0x35, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x47, 0x42, 0x35, 0x35, 0x35,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x59, 0x55, 0x56, 0x34, 0x32, 0x30, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x59, 0x55, 0x56, 0x34, 0x32, 0x32, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x59, 0x55,
	0x56, 0x34, 0x34, 0x34, 0x10, 0x05, 0x22, 0x33, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44,
	0x72, 0x6f, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x7f, 0x0a, 0x0f, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x77, 0x53, 0x51, 0x4c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x61, 0x77, 0x53, 0x51, 0x4c, 0x22, 0x9e, 0x01, 0x0a,
	0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x46, 0x0a, 0x10, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x28, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x51, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5b, 0x0a, 0x10, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x46, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2a,
	0xce, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x49, 0x6e, 0x74, 0x38, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x49, 0x6e, 0x74, 0x38, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x31, 0x36, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x49, 0x6e, 0x74, 0x31, 0x36, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x10, 0x05, 0x12,
	0x07, 0x0a, 0x03, 0x49, 0x6e, 0x74, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x49, 0x6e, 0x74,
	0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x10, 0x08, 0x12, 0x0a, 0x0a,
	0x06, 0x55, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x10, 0x0b,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x0c, 0x12, 0x09, 0x0a, 0x05,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x10, 0x0d, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x10,
	0x0e, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6c,
	0x10, 0x0f, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x74, 0x69, 0x6d, 0x65, 0x10, 0x10,
	0x32, 0xc9, 0x01, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x3b,
	0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3c,
	0x0a, 0x05, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x17, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x7f, 0x0a, 0x09,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x35, 0x0a, 0x0f, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x6e, 0x63, 0x65, 0x12, 0x0f, 0x2e, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x1a, 0x0f, 0x2e,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0f, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x1a, 0x0f, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x15, 0x5a,
	0x13, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_functions_proto_rawDescOnce sync.Once
	file_functions_proto_rawDescData = file_functions_proto_rawDesc
)

func file_functions_proto_rawDescGZIP() []byte {
	file_functions_proto_rawDescOnce.Do(func() {
		file_functions_proto_rawDescData = protoimpl.X.CompressGZIP(file_functions_proto_rawDescData)
	})
	return file_functions_proto_rawDescData
}

var file_functions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_functions_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_functions_proto_goTypes = []interface{}{
	(DataType)(0),            // 0: functions.DataType
	(Image_ImageFormat)(0),   // 1: functions.Image.ImageFormat
	(*Drop)(nil),             // 2: functions.Drop
	(*Properties)(nil),       // 3: functions.Properties
	(*DeviceDropItem)(nil),   // 4: functions.DeviceDropItem
	(*DeviceDrop)(nil),       // 5: functions.DeviceDrop
	(*AudioDrop)(nil),        // 6: functions.AudioDrop
	(*Image)(nil),            // 7: functions.Image
	(*ImageDrop)(nil),        // 8: functions.ImageDrop
	(*ObjectCondition)(nil),  // 9: functions.ObjectCondition
	(*GeneratorRequest)(nil), // 10: functions.GeneratorRequest
	(*ProbeRequest)(nil),     // 11: functions.ProbeRequest
	(*ObjectItem)(nil),       // 12: functions.ObjectItem
	(*ObjectDefination)(nil), // 13: functions.ObjectDefination
	(*ProbeResponse)(nil),    // 14: functions.ProbeResponse
	nil,                      // 15: functions.DeviceDropItem.PropertiesEntry
}
var file_functions_proto_depIdxs = []int32{
	5,  // 0: functions.Drop.deviceDrop:type_name -> functions.DeviceDrop
	6,  // 1: functions.Drop.audioDrop:type_name -> functions.AudioDrop
	8,  // 2: functions.Drop.imageDrop:type_name -> functions.ImageDrop
	0,  // 3: functions.Properties.datatype:type_name -> functions.DataType
	15, // 4: functions.DeviceDropItem.properties:type_name -> functions.DeviceDropItem.PropertiesEntry
	4,  // 5: functions.DeviceDrop.items:type_name -> functions.DeviceDropItem
	1,  // 6: functions.Image.format:type_name -> functions.Image.ImageFormat
	7,  // 7: functions.ImageDrop.image:type_name -> functions.Image
	9,  // 8: functions.GeneratorRequest.objectConditions:type_name -> functions.ObjectCondition
	0,  // 9: functions.ObjectItem.datatype:type_name -> functions.DataType
	12, // 10: functions.ObjectDefination.items:type_name -> functions.ObjectItem
	13, // 11: functions.ProbeResponse.objects:type_name -> functions.ObjectDefination
	3,  // 12: functions.DeviceDropItem.PropertiesEntry.value:type_name -> functions.Properties
	10, // 13: functions.Generator.QueryData:input_type -> functions.GeneratorRequest
	10, // 14: functions.Generator.SubscribeData:input_type -> functions.GeneratorRequest
	11, // 15: functions.Generator.Probe:input_type -> functions.ProbeRequest
	2,  // 16: functions.Processor.ProcessDataOnce:input_type -> functions.Drop
	2,  // 17: functions.Processor.ProcessDataStream:input_type -> functions.Drop
	2,  // 18: functions.Generator.QueryData:output_type -> functions.Drop
	2,  // 19: functions.Generator.SubscribeData:output_type -> functions.Drop
	14, // 20: functions.Generator.Probe:output_type -> functions.ProbeResponse
	2,  // 21: functions.Processor.ProcessDataOnce:output_type -> functions.Drop
	2,  // 22: functions.Processor.ProcessDataStream:output_type -> functions.Drop
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_functions_proto_init() }
func file_functions_proto_init() {
	if File_functions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_functions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Drop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Properties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceDropItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceDrop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioDrop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageDrop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectDefination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_functions_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_functions_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Drop_DeviceDrop)(nil),
		(*Drop_AudioDrop)(nil),
		(*Drop_ImageDrop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_functions_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_functions_proto_goTypes,
		DependencyIndexes: file_functions_proto_depIdxs,
		EnumInfos:         file_functions_proto_enumTypes,
		MessageInfos:      file_functions_proto_msgTypes,
	}.Build()
	File_functions_proto = out.File
	file_functions_proto_rawDesc = nil
	file_functions_proto_goTypes = nil
	file_functions_proto_depIdxs = nil
}
